version: "3"

services:
  ochaindnode0:
    container_name: ochaindnode0
    image: "onomy/ochain"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-ochaind.log}
    volumes:
      - ./build:/ochaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  ochaindnode1:
    container_name: ochaindnode1
    image: "onomy/ochain"
    ports:
      - "26666-26667:26656-26657"
      - "1318:1317"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-ochaind.log}
    volumes:
      - ./build:/ochaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  ochaindnode2:
    container_name: ochaindnode2
    image: "onomy/ochain"
    environment:
      - ID=2
      - LOG=${LOG:-ochaind.log}
    ports:
      - "26676-26677:26656-26657"
      - "1319:1317"
      - "9092:9090"
    volumes:
      - ./build:/ochaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  ochaindnode3:
    container_name: ochaindnode3
    image: "onomy/ochain"
    environment:
      - ID=3
      - LOG=${LOG:-ochaind.log}
    ports:
      - "26686-26687:26656-26657"
      - "1320:1317"
      - "9093:9090"
    volumes:
      - ./build:/ochaind:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/16
