name: Development Testnet
on: [ push, pull_request ]

jobs:
  amd64:
    name: fury-hub Docker
    environment: test
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes --credential yes

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push blockchain
        run: docker buildx build --tag onomy/ochain-testnet --file deploy/docker/testnet/Dockerfile --platform linux/amd64 --cache-from onomy/ochain-testnet:cache --cache-to onomy/ochain-testnet:cache --push --progress tty .