name: Release

on:
  release:
    types: [ published ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v2.x

      - if: contains(github.ref, 'devnet')
        run: |
          echo "CHAINNET=testnet" >> "$GITHUB_ENV"

      - if: contains(github.ref, 'testnet')
        run: |
          echo "CHAINNET=testnet" >> "$GITHUB_ENV"

      - if: contains(github.ref, 'mainnet')
        run: |
          echo "CHAINNET=mainnet" >> "$GITHUB_ENV"

      - name: Build docker images
        run: |
          echo ${{ env.CHAINNET }}
          make CHAINNET=${{ env.CHAINNET }} IMAGE_TAG=${{ env.GITHUB_REF_SLUG }} BINARY=ochaind build-image

      - name: Push docker images
        run: |
          docker push onomy/ochaind:${{ env.GITHUB_REF_SLUG }}

      - name: Release a new ochaind binary
        uses: ./deploy/release
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: linux
          goarch: amd64
          goversion: "https://dl.google.com/go/go1.15.1.linux-amd64.tar.gz"
          project_path: "./cmd/ochaind"
          binary_name: "ochaind"
          sha256sum: true